### ISSUE TITLE
og 개선하기

### ISSUE THREAD

**Issue by joi0104** [mash-up-kr/Nawa-Invitation-Web#100]
## 설명
og title 과 description, image을 동적으로 변경을 위한 og 개선하기

## 작업 단위
- [ ] 미정 

## 참고사항
참고사항 기재

**Comment by danivelop** [comment]
해당 작업은 #98과 같이 작업이 되야할 것 같아서 하나는 클로즈하고 다른 하나로 내용 합치면 어떨까요?

**Comment by joi0104** [comment]
넵 알겠습니다!
