### ISSUE TITLE
레포지토리 이슈템플릿 만들기

### ISSUE THREAD

**Issue by danivelop** [mash-up-kr/Nawa-Invitation-Web#21]
지금은 이렇게 아무템플릿도 없지만 이슈템플릿 만들어서 이슈작성 깔끔하게 하고싶다...

**Comment by joi0104** [comment]
저두용..ㅋㅋㅋㅋㅋㅋㅋ 이번에 커밋 메시지 템플릿이랑 이슈 템플릿 만들어보죠!

**Comment by danivelop** [comment]
오! 초안 작성해주시면 감사하죠ㅎㅎ 초안에서 추가됐으면 하는 내용들 상의해서 조금씩 추가해나가면 좋을것같아요

**Comment by kor-Chipmunk** [comment]
안녕하세용! 디오니소스팀 백엔드팀입니당!
매셥 알람이 이메일로 오다보니 우연찮게 보게됐네요~
저희는 이슈 템플릿 요로케 하고 있어요!

---

## 목적
목적을 기입해주세요.

## 작업 상세 내용
- [ ] 작업1
- [ ] 작업2

## 참고사항
참고사항들을 알려주세요.

---

[저희 팀 레포지토리 이슈](https://github.com/mash-up-kr/Dionysos-Backend/issues)에서 사용 예시 자세하게 확인할 수 있습니다!

<img width="934" alt="스크린샷 2020-07-28 오후 5 53 03" src="https://user-images.githubusercontent.com/16275188/88642260-38691180-d0fb-11ea-8a4b-8cafa3a0af47.png">

---

커밋 메시지 템플릿도 있다는 걸 요번에 알았네요..!
저희도 적용해 보아야겠네요~
좋은거 알려주셔서 감사합니당~

**Comment by joi0104** [comment]
와 감사합니다! 참고해서 템플릿 만들고 여기에 공유하겠습니다! 참고로 물어볼께 있는데, 대용오빠가 작성해주신 pr 템플릿 경우 pr 생성할 때 자동으로 템플릿이 적용되거든요. 현재 디오니소스 팀에서 작성한 이슈 템플릿도 이슈 작성할때 자동으로 적용이 되나요? 된다면 방법 공유 부탁드립니다!

**Comment by kor-Chipmunk** [comment]
네! 깃허브 이슈 생성할 때 여러 템플릿들을 고를 수 있습니다!
Settings 메뉴의 Features 목록 Issue 항목의 Set up templates 로 템플릿 만들 수 있습니당.

**Comment by joi0104** [comment]
감사합니다!

**Comment by joi0104** [comment]
이슈 템플릿은 다음과 같이 작성하였습니다. 


# Title
default title은 `이슈 등록하기`로 되어있습니다. `~기` 형식으로 Title 작성 부탁드립니다.

# Content
default content는 다음과 같이 되어있습니다. 다음과 같은 형식으로 Content 작성 부탁드립니다.
<img width="839" alt="image" src="https://user-images.githubusercontent.com/28296417/89177660-e4f93680-d5c6-11ea-91a9-4c4a6b079945.png">
